Backend get attacking numbers
Campus-Capture/campus-capture pull request #136
Opened 2023-05-11 21:26 UTC by r-temp

Implements the backend function to know who attacks a zone.

2023-05-15 10:09 UTC, Jenjamin3000 requested changes
This is great work! However, it does not always work. I think there is a problem with the owner of the zone. This is present in the DB but this is not checked which causes the program to crash. Can you just fix this before the merge, if it is possible?

2023-05-16 08:47 UTC, r-temp commented
Sorry I cannot replicate the issue, is there a specific zone that crash when clicked ?
Though I have noticed there seems to be a bug in the UI, it fetches the attacks count from the DB when the polygon of a zone is clicked but not when the label is, so you need to really click near the edge of a poly to see "Current attacks:" appears. Of course no attacks are shown because nobody play the game currently, if you add votes in the DB to test make sure the type is number and not string else you will get a cast exception in the app.

2023-05-16 10:02 UTC, Jenjamin3000 commented
My bad! I did not see that the chowing of the number of attacks was enable only during the takeover which totally makes sense. All is good!

2023-05-16 10:04 UTC, Jenjamin3000 approved these changes
LGTM! All is OK, good job!

2023-05-16 10:04 UTC, Jenjamin3000 commented on app/src/main/java/com/github/campus_capture/bootcamp/firebase/FirebaseBackend.java
> +                            // expected exception for the "owner" child which is not a section
For now it works, I think it will be alright for now. However, I believe that you are right, a condition may be cleaner.

2023-05-16 12:49 UTC, merged