Testing Profile and minor refactoring
Campus-Capture/campus-capture pull request #148
Opened 2023-05-18 15:50 UTC by Blopgrop

poking CI let's  gooo

2023-05-18 18:29 UTC, Ant-One requested changes

2023-05-18 18:29 UTC, Ant-One commented on app/src/androidTest/java/com/github/campus_capture/bootcamp/activities/AuthenticationActivityTest.java
> +        assertThat(Intents.getIntents().isEmpty(), is(false));
This assertion fails on my machine locally. Is the intent in another PR not yet completed?

2023-05-30 16:26 UTC, Jenjamin3000 approved these changes
LGTM, all is working for me. Nice refactor! That seems much clearer!

2023-05-30 18:29 UTC, Jenjamin3000 approved these changes
LSGADTM! Looks still good as duck to me!

2023-05-30 18:34 UTC, Ant-One approved these changes

2023-05-30 18:36 UTC, merged