Make the app look nice :)
Campus-Capture/campus-capture pull request #155
Opened 2023-05-19 07:32 UTC by Blopgrop

2023-05-25 14:22 UTC, Jenjamin3000 commented on app/src/androidTest/java/com/github/campus_capture/bootcamp/MapVoteTest.java
> +import org.junit.Ignore;
I think this is an old import, if you can just optimize the imports it would be perfect.

2023-05-25 14:23 UTC, Jenjamin3000 commented on app/src/main/java/com/github/campus_capture/bootcamp/firebase/FirebaseBackend.java
> +                        Section owner = s_owner.equals("null") ? Section.NONE : Section.valueOf(s_owner);
Nice! The app will be more robust like that!

2023-05-25 14:27 UTC, Jenjamin3000 commented on app/src/main/res/values/strings.xml
There is a lot of strings that are unused. Maybe it would be great to remove those.

2023-05-25 14:35 UTC, Jenjamin3000 requested changes
This is awesome! The app is so much better like this! Great job! There is just one or two things I found a little bit perturbing. In the main activity, 
- The text name the zone the user is in, is white on a white background which makes it difficult to read. 
- When not on a takeover, the attack button does not show anymore the time before the next takeover. Is it normal?

After those changes, all will be good for me! Good job!

2023-05-25 14:41 UTC, Blopgrop commented on app/src/main/res/values/strings.xml
I think it will be taken cared of by the people that do the translation but it is a good remark yes

2023-05-25 14:47 UTC, Blopgrop commented
So the bugs that you are pointing out are due to the fact that your phone is probably in dark mode which is _there_ but not fully implemented yet. I have made a task to solve those exact issues.

As of right now if you test the app in light mode (yeah I'm already sorry for your eyes lol) those problem should be taken cared of.

2023-05-25 14:59 UTC, Jenjamin3000 commented
Oh I see, it is even more gorgeous in light mode! There is so just still the Attack button. Can you maybe reduce a little bit the size of the text in order to show the time before the next Takeover?

2023-05-30 16:49 UTC, Jenjamin3000 commented on app/src/main/res/layout/nav_header_navigation_drawer.xml
> -    android:paddingBottom="@dimen/activity_vertical_margin"
Nice! This is so much better without that android logo!

2023-05-30 16:54 UTC, Jenjamin3000 approved these changes
LGTM! Nice!!! This is so much better! Good job!

2023-05-30 18:19 UTC, merged